/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iesvdc.lmsgi;

import java.awt.Component;
import java.awt.Dimension;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author matinal
 */
public class JFrameXML extends javax.swing.JFrame {

    /**
     * Creates new form JFrameXML
     */
    public JFrameXML() {
        getProperties();
        initComponents();
        jTextAreaResultadoDTD_XSD.setTabSize(4);
        jTextAreaResultadoXPath.setTabSize(4);
        jTextAreaResultadoXslt.setTabSize(4);
        jTextAreaXML_DTD_XSD.setTabSize(4);
        jTextAreaXPATH.setTabSize(4);
        jTextAreaXSD_DTD.setTabSize(4);
        jTextAreaXml_Xslt.setTabSize(4);
        jTextAreaXslt.setTabSize(4);
        jLabel4.setMaximumSize(new Dimension(jTextAreaResultadoXslt.getWidth(),jTextAreaResultadoXslt.getHeight()));
        grupo.add(radioXSD);
        grupo.add(radioDTD);
        filterXML = new FileNameExtensionFilter("XML file", "xml", "XML");
        jFileChooserXML.addChoosableFileFilter(filterXML);
        filterHTML = new FileNameExtensionFilter("html file", "html", "htm");
        jFileChooserXML.addChoosableFileFilter(filterHTML);
        filterDTD = new FileNameExtensionFilter("DTD file", "dtd");
        jFileChooserXML.addChoosableFileFilter(filterDTD);
        filterXSD = new FileNameExtensionFilter("XSD file", "xsd");
        jFileChooserXML.addChoosableFileFilter(filterXSD);
        filterXSLT = new FileNameExtensionFilter("xslt file", "xsl");
        jFileChooserXML.addChoosableFileFilter(filterXSLT);
        filterXQ = new FileNameExtensionFilter("xquery file", "xq", "xquery");
        jFileChooserXML.addChoosableFileFilter(filterXQ);
        listarLookAndFeel();
        obtenerNombreLucas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserXML = new javax.swing.JFileChooser();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        grupo = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaXML_DTD_XSD = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaResultadoDTD_XSD = new javax.swing.JTextArea();
        jButtonCargarDTD = new javax.swing.JButton();
        jButtonvalidarDTD = new javax.swing.JButton();
        radioXSD = new javax.swing.JRadioButton();
        radioDTD = new javax.swing.JRadioButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextAreaXSD_DTD = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldXPath = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaResultadoXPath = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaXPATH = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaXml_Xslt = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextAreaXslt = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextAreaResultadoXslt = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jMenu6.setText("File");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar2.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaXML_DTD_XSD.setColumns(20);
        jTextAreaXML_DTD_XSD.setRows(5);
        jScrollPane3.setViewportView(jTextAreaXML_DTD_XSD);

        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Cargar XML");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextAreaResultadoDTD_XSD.setColumns(20);
        jTextAreaResultadoDTD_XSD.setRows(5);
        jScrollPane7.setViewportView(jTextAreaResultadoDTD_XSD);

        jButtonCargarDTD.setText("Cargar XSD");
        jButtonCargarDTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarDTDActionPerformed(evt);
            }
        });

        jButtonvalidarDTD.setText("Validar");
        jButtonvalidarDTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonvalidarDTDActionPerformed(evt);
            }
        });

        radioXSD.setSelected(true);
        radioXSD.setText("XSD");
        radioXSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioXSDActionPerformed(evt);
            }
        });

        radioDTD.setText("DTD");
        radioDTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDTDActionPerformed(evt);
            }
        });

        jTextAreaXSD_DTD.setColumns(20);
        jTextAreaXSD_DTD.setRows(5);
        jScrollPane9.setViewportView(jTextAreaXSD_DTD);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonvalidarDTD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radioXSD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radioDTD)))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                                .addComponent(jButtonCargarDTD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9)))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonvalidarDTD)
                    .addComponent(jButton4)
                    .addComponent(radioXSD)
                    .addComponent(radioDTD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButtonCargarDTD)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Validar XSD/DTD", jPanel1);

        jTextFieldXPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldXPathActionPerformed(evt);
            }
        });

        jTextAreaResultadoXPath.setEditable(false);
        jTextAreaResultadoXPath.setColumns(20);
        jTextAreaResultadoXPath.setRows(5);
        jScrollPane1.setViewportView(jTextAreaResultadoXPath);

        jTextAreaXPATH.setEditable(false);
        jTextAreaXPATH.setColumns(20);
        jTextAreaXPATH.setRows(5);
        jScrollPane2.setViewportView(jTextAreaXPATH);

        jButton1.setText("Evaluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cargar XML");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldXPath, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldXPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("xPath", jPanel3);

        jButton8.setText("Ejecutar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Cargar XSLT");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Cargar XML");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTextAreaXml_Xslt.setColumns(20);
        jTextAreaXml_Xslt.setRows(5);
        jScrollPane4.setViewportView(jTextAreaXml_Xslt);

        jTextAreaXslt.setColumns(20);
        jTextAreaXslt.setRows(5);
        jScrollPane8.setViewportView(jTextAreaXslt);

        jTextAreaResultadoXslt.setEditable(false);
        jTextAreaResultadoXslt.setColumns(20);
        jTextAreaResultadoXslt.setRows(5);
        jScrollPane11.setViewportView(jTextAreaResultadoXslt);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(256, 267, Short.MAX_VALUE))
                    .addComponent(jScrollPane8)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton9)
                        .addComponent(jButton8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("XSLT", jPanel4);

        jLabel5.setText("<html><h4>Proyecto desarrollado por:</h4></</html>");

        jLabel6.setText("<html><h4>Damos gracias al maravilloso método <strike>getComponent()</strike> por todo esa gran sabiduria con la que nos ha dotado. Y paciencia...</h4></</html>");

        jLabel7.setText("<html><h4>Rafael Vargas del Moral</h4></</html>");

        jLabel8.setText("<html><h4>David Martínez Tuñón</h4></</html>");

        jLabel9.setText("<html><h4>Manuel Quesada Segura</h4></</html>");

        jLabel10.setText("<html><h4>Javier García Fernández-Medina</h4></</html>");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(9, 9, 9)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap(283, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap(203, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(95, 95, 95)))
        );

        jTabbedPane1.addTab("about", jPanel6);

        jMenu1.setText("File");

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Settings");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenu5.setText("Look & Feel");
        jMenu5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMenu5FocusGained(evt);
            }
        });
        jMenu5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jMenu5ComponentResized(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    boton cargar xml de xslt
     */
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jFileChooserXML.setFileFilter(filterXML);
        int returnVal = jFileChooserXML.showOpenDialog(JFrameXML.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserXML.getSelectedFile();
            String contenido = "";
            try (Scanner sc = new Scanner(file);) {

                while (sc.hasNextLine()) {
                    contenido += sc.nextLine() + "\n";
                    jTextAreaXml_Xslt.setText(/*"cargando archivo:\n" + file.getName() + "\n" +*/contenido);
                    if (controller == null) {
                        controller = new Controller(file);
                    } else {
                        controller.setFile(file);
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(JFrameXML.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {

        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /*
    cargar xslt
     */
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jFileChooserXML.setFileFilter(filterXSLT);
        int returnVal = jFileChooserXML.showOpenDialog(JFrameXML.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserXML.getSelectedFile();
            String contenido = "";
            try (Scanner sc = new Scanner(file);) {

                while (sc.hasNextLine()) {
                    contenido += sc.nextLine() + "\n";
                    jTextAreaXslt.setText(/*"cargando archivo:\n" + file.getName() + "\n" +*/contenido);
                    if (controller == null) {
                        controller = new Controller(file);
                       // controller.setFileXSL(file);
                    } else {
                        controller.setFileXSL(file);
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(JFrameXML.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {

        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /*
    ejecutar xslt
     */
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (!(jTextAreaXml_Xslt.getText().equals("") || jTextAreaXslt.getText().equals("") || jTextAreaXslt==null || jTextAreaXml_Xslt==null )) {
            jFileChooserXML.setFileFilter(filterHTML);
            int returnVal = jFileChooserXML.showSaveDialog(JFrameXML.this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = jFileChooserXML.getSelectedFile();

                controller.save2xsl(jTextAreaXslt.getText());
                controller.save2xml(jTextAreaXml_Xslt.getText());
                jTextAreaResultadoXslt.setText(controller.xslTransform());

                if (controller == null) {
                    controller = new Controller(file);
                } else {
                    controller.setFileHTML(file);
                }
                try (Scanner sc = new Scanner(controller.getFileHTML());) {
                    String resultado = "";
                    while (sc.hasNextLine()) {
                        resultado += sc.nextLine() + "\n";
                    }

                    jTextAreaResultadoXslt.setText(resultado);
                    jLabel4.setText(resultado);
                } catch (FileNotFoundException ex) {

                }
            }
    }//GEN-LAST:event_jButton8ActionPerformed
    }
    /*
    boton limpiar xpath
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextFieldXPath.setText("");
        jTextAreaXPATH.setText("");
        jTextAreaResultadoXPath.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /*
    boton para cargar el xml al que le vamos a hacer la expresion xpath
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jFileChooserXML.setFileFilter(filterXML);
        int returnVal = jFileChooserXML.showOpenDialog(JFrameXML.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserXML.getSelectedFile();
            String contenido = "";
            try (Scanner sc = new Scanner(file);) {

                while (sc.hasNextLine()) {
                    contenido += sc.nextLine() + "\n";
                    jTextAreaXPATH.setText(/*"cargando archivo:\n" + file.getName() + "\n" +*/contenido);
                    if (controller == null) {
                        controller = new Controller(file);
                    } else {
                        controller.setFile(file);
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(JFrameXML.class.getName()).log(Level.SEVERE, null, ex);
            }
            jLabel3.setText(file.getName());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /*
    boton evaluar expresion xpath
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!(jTextAreaXPATH.getText().equals("") || jTextFieldXPath.getText().equals(""))) {
            jTextAreaResultadoXPath.setText(controller.xPathEvaluate(jTextFieldXPath.getText()));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldXPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldXPathActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldXPath.getText().isEmpty()) {
            jTextAreaResultadoXPath.setText(controller.xPathEvaluate(jTextFieldXPath.getText()));
        }
    }//GEN-LAST:event_jTextFieldXPathActionPerformed

    /*
    boton para validar dtd
     */

    private void jButtonvalidarDTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonvalidarDTDActionPerformed
        // TODO add your handling code here:
        if (!(jTextAreaXML_DTD_XSD.getText().equals(""))){
            if (radioDTD.isSelected()) {
                controller.save2xml(jTextAreaXML_DTD_XSD.getText());
                jTextAreaResultadoDTD_XSD.setText(controller.validar());
                
            } else if (radioXSD.isSelected()) {
                
                controller.save2xml(jTextAreaXML_DTD_XSD.getText());
                controller.save2DTD(jTextAreaXSD_DTD.getText());
                jTextAreaResultadoDTD_XSD.setText(controller.validateXSD());
            }
        }
    }//GEN-LAST:event_jButtonvalidarDTDActionPerformed

    private void jButtonCargarDTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarDTDActionPerformed
        // TODO add your handling code here:
        jFileChooserXML.setFileFilter(filterXSD);
        int returnVal = jFileChooserXML.showOpenDialog(JFrameXML.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserXML.getSelectedFile();
            String contenido = "";
            try (Scanner sc = new Scanner(file);) {

                while (sc.hasNextLine()) {
                    contenido += sc.nextLine() + "\n";
                    jTextAreaXSD_DTD.setText(contenido);
                    if (controller == null) {
                        controller = new Controller(file);
                    } else {
                        controller.setFileDTD(file);
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(JFrameXML.class.getName()).log(Level.SEVERE, null, ex);
            }
            jLabel2.setText(file.getName());
        }
    }//GEN-LAST:event_jButtonCargarDTDActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jFileChooserXML.setFileFilter(filterXML);
        int returnVal = jFileChooserXML.showOpenDialog(JFrameXML.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserXML.getSelectedFile();
            String contenido = "";
            try (Scanner in = new Scanner(file);) {
                while (in.hasNextLine()) {
                    contenido += in.nextLine() + "\n";
                    jTextAreaXML_DTD_XSD.setText(contenido);
                    jTextAreaXml_Xslt.setText(contenido);
                    jTextAreaXPATH.setText(contenido);
                }

            } catch (FileNotFoundException ex) {
                //Logger.getLogger(JFrameXML.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (controller == null) {
                controller = new Controller(file);
            } else {
                controller.setFile(file);
            }
            jLabel1.setText(file.getName());
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextAreaXML_DTD_XSD.setText("");
        jTextAreaResultadoDTD_XSD.setText("");
        jTextAreaXSD_DTD.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void radioDTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDTDActionPerformed
        // TODO add your handling code here:
        jButtonCargarDTD.setEnabled(false);
        jTextAreaXSD_DTD.setEnabled(false);
        jTextAreaXSD_DTD.setText("");
        jLabel2.setText("");
    }//GEN-LAST:event_radioDTDActionPerformed

    private void radioXSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioXSDActionPerformed
        jButtonCargarDTD.setEnabled(true);
        jTextAreaXSD_DTD.setEnabled(true);
    }//GEN-LAST:event_radioXSDActionPerformed

    private void jMenu5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenu5FocusGained

    }//GEN-LAST:event_jMenu5FocusGained

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed


    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked

    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenu5ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jMenu5ComponentResized

    }//GEN-LAST:event_jMenu5ComponentResized

    public boolean getProperties() {
        Properties prop = new Properties();
        InputStream input = null;
        boolean correcto = true;

        try {
            input = new FileInputStream("config.properties");
            prop.load(input);
            // get the properties value
            menuSeleccionado = prop.getProperty("lookandfeel");
            // save properties to project root folder
            //output.close();
            if (this.menuSeleccionado == null) {
                this.menuSeleccionado = "Nimbus";
            }
        } catch (IOException io) {
            correcto = false;
        } finally {
            if (input != null) {
                try {
                    input.close();
                } catch (IOException e) {
                    correcto = false;
                }
            }
        }
        return correcto;
    }

    public String[] listarLookAndFeel() {
        String[] look = new String[UIManager.getInstalledLookAndFeels().length];
        for (int i = 0; i < UIManager.getInstalledLookAndFeels().length; i++) {
            look[i] = UIManager.getInstalledLookAndFeels()[i].getName().toString();
        }
        crearListaDinamica(look);
        return look;
    }

    public void crearListaDinamica(String[] stringArray) {
        for (int i = 0; i < stringArray.length; i++) {
            jmenu = new JMenuItem(stringArray[i]);
            jMenu5.add(jmenu);
        }
    }

    /* 
    boton limpiar xsd
     */
 /*
    boton para limpiar los jtextarea del dtd
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            Properties prop = new Properties();
            InputStream input = new FileInputStream("config.properties");
            prop.load(input);
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                System.out.println(prop.getProperty("lookandfeel"));
                if (prop.getProperty("lookandfeel").equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameXML().setVisible(true);
            }
        });
    }

    public void obtenerNombreLucas() {

        for (int i = 0; i < jMenu5.getItemCount(); i++) {
            JMenuItem menu = (JMenuItem) jMenu5.getItem(i);
            menu.addActionListener(r -> {
                Properties prop = new Properties();
                OutputStream output = null;
                menuSeleccionado = menu.getText();
                try {
                    output = new FileOutputStream("config.properties");
                    // set the properties value
                    if (this.menuSeleccionado != null) {
                        prop.setProperty("lookandfeel", this.menuSeleccionado);
                    } else {
                        prop.setProperty("lookandfeel", "Nimbus");
                    }
                    prop.store(output, null);
                    // output.close();
                } catch (IOException io) {

                } finally {
                    if (output != null) {
                        try {
                            output.close();
                        } catch (IOException e) {

                        }
                    }
                }
            });
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonCargarDTD;
    private javax.swing.JButton jButtonvalidarDTD;
    private javax.swing.JFileChooser jFileChooserXML;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaResultadoDTD_XSD;
    private javax.swing.JTextArea jTextAreaResultadoXPath;
    private javax.swing.JTextArea jTextAreaResultadoXslt;
    private javax.swing.JTextArea jTextAreaXML_DTD_XSD;
    private javax.swing.JTextArea jTextAreaXPATH;
    private javax.swing.JTextArea jTextAreaXSD_DTD;
    private javax.swing.JTextArea jTextAreaXml_Xslt;
    private javax.swing.JTextArea jTextAreaXslt;
    private javax.swing.JTextField jTextFieldXPath;
    private javax.swing.JRadioButton radioDTD;
    private javax.swing.JRadioButton radioXSD;
    // End of variables declaration//GEN-END:variables
    private FileFilter filterXML;
    private FileFilter filterHTML;
    private FileFilter filterDTD;
    private FileFilter filterXSD;
    private FileFilter filterXSLT;
    private FileFilter filterXQ;
    private Controller controller;
    private JMenuItem jmenu;
    private String menuSeleccionado;
    
    
}
